Repository hackupc/myhackupc, pull requests merged in 2024-04, with the labels that each got.

#314 [dev to master] Extend volunteer application time
  app/hackathon_variables.py
Labels: enhancement

#306 Migrated and finished styles for Google Wallet Ticket Pass
  .env.template
  app/gwallet/__init__.py
  app/gwallet/eventticket.py
  app/settings.py
  app/utils.py
  applications/views.py
  docker-compose.yaml
Labels: enhancement

#316 FiX: Moved to stable QR API
  applications/templates/dashboard.html
Labels: bug

#319 Replace logo and starting time of G Wallet Pass
  app/utils.py
Labels: enhancement

#300 Change expiration date for travel tickets uploading
  app/hackathon_variables.py
  app/utils.py
  reimbursement/models.py
Labels: DO NOT MERGE

#320 Remove G wallet pass qr alternate text
  app/utils.py
Labels: enhancement

#318 DEVELOP TO MASTER
  .env.template
  app/gwallet/__init__.py
  app/gwallet/eventticket.py
  app/hackathon_variables.py
  app/settings.py
  app/utils.py
  applications/templates/dashboard.html
  applications/views.py
  docker-compose.yaml
  organizers/templates/application_detail.html
  reimbursement/models.py
  server.sh.template
Labels: enhancement

#329 Fix URL and double ajax propagation on HW
  app/static/js/scanner_old.js
  baggage/templates/baggage_currenthacker.html
  hardware/static/js/hw_admin.js
Labels: bug

#330 Add under_age alert on checkin
  checkin/templates/checkin/hacker.html
  checkin/templates/include/field_status.html
  checkin/templates/include/field_under_age.html
Labels: enhancement
